#' Import a Normalized CBC CSV File
#'
#' \code{ImportCbcCsv} takes a file generated by the CBC-CSV-CLI (C3) tool.
#'
#' @param file A CSV file
#' @return a \code{cbc.count} object
#' @export
ImportCbcCsv <- function(csv.file) {
  cbc.count <- read.csv(csv.file)
  return(cbc.count)
}

#' Select a Bird Species
#'
#' \code{SelectSpecies} takes a \code{cbc.count} object and a \code{species.name}
#'   string and returns a \code{bird} object.
#'
#' @param cbc.count A \code{cbc.count} object
#' @param species.name A bird species name string
#' @return a \code{bird.species} object
#' @export
SelectSpecies <- function(cbc.count, species.name) {
  bird.species <- cbc.count[cbc.count$Species == species.name, ][ ,-1]
  return(bird.species)
}

#' Draws a Barplot of a Bird Species
#'
#' \code{DrawBirdSpeciesBarplot} will create a barplot graph of a bird species.
#'
#' @param bird.species A bird species object
#' @param bird.name A name to put on the graph
#' @export
DrawBirdSpeciesBarplot <- function(bird.species,
                                   bird.name = "") {
  bird.data <- as.matrix(bird.species)

  barplot(bird.data,
          main      = bird.name,
          sub       = "CBC Data",
          xlab      = "Years",
          ylab      = "Count",
          col       = "blue",
          cex.names = 0.675,
          las       = 2)
}
