#' Import a Normalized CBC CSV File
#'
#' \code{ImportCbcCsv} takes a file generated by the CBC-CSV-CLI (C3) tool.
#'
#' @param csv.file A CSV file
#' @param cbc.name Optional. The name of the CBC
#' @return a \code{cbc} list object
#' @export
ImportCbcCsv <- function(csv.file, cbc.name="") {
  count.data <- read.csv(csv.file)
  count.code <- substring(csv.file, 8, 11)
  count.name <- cbc.name
  cbc <- list(data=count.data, code=count.code, name=count.name)
  return(cbc)
}

#' Select a Bird Species
#'
#' \code{SelectSpecies} takes a \code{cbc.count} object and a \code{species.name}
#'   string and returns a \code{bird} object.
#'
#' @param cbc A \code{cbc} list object
#' @param species.name A bird species or taxon name string
#' @return a \code{bird} list object
#' @export
SelectSpecies <- function(cbc, species.name) {
  species.count <- cbc$data[cbc$data$Species == species.name, ]
  bird <- list(count=species.count, name=species.name)
  return(bird)
}

#' Generates Barplot SVGs for All Taxons in a Count
#'
#' \code{GenerateAllSvgs} will create SVGs for all taxons.
#'
#' @param \code{cbc} The CBC count vector
#' @export
GenerateAllSvgs <- function(cbc) {
  for(i in 1:nrow(cbc$data)) {
    bird.row <- SelectSpecies(cbc, cbc$data[i, 1])
    DrawBirdSpeciesBarplot(bird.row, generate.svg = T, cbc.code = cbc$code, cbc.name = cbc$name)
  }
}

#' Converts a species or taxon name to be filename-safe
#'
#' \code{FileSafeName} will take a string and return one that is safe as a filename
#'
#' @param sx A string
#' @return A string
FileSafeName <- function(sx) {
  result <- gsub("(\\/)", "_or_", sx)
  result <- gsub("(sp\\.)$", "sp", result)
  return(result)
}

#' Makes a directory for SVGs of a CBC, if it does not already exist
#'
#' \code{MakeSvgDirectory} will create a sub-directory if it doesn't exist yet in the ./svgs folder
#' @param sx A string
MakeSvgDirectory <- function(sx) {
  svg.dir <- paste0("svgs/", sx)
  cwd <- getwd()
  dir.create(file.path(cwd, svg.dir), showWarnings = FALSE)
}

#' Removes the 'X' prefix from column names in data frames that are years
#'
#' \code{RemoveXHeaders} will remove the prefix 'X' from a data frame's headers
#'
#' @param df A data frame
RemoveXHeaders <- function(df) {
  names(df)[-1] <- substring(names(df)[-1], 2)
  return(df)
}

#' Draws a Barplot of a Bird Species
#'
#' \code{DrawBirdSpeciesBarplot} will create a barplot graph of a bird species.
#'
#' @param bird A bird species list object
#' @param main.title A title to put on the graph; if not provided, species name used
#' @param generate.svg Generates an SVG image
#' @param cbc.code The code for the CBC
#' @export
DrawBirdSpeciesBarplot <- function(bird,
                                   main.title = "",
                                   generate.svg = F,
                                   cbc.code = "_CBC",
                                   cbc.name = "") {
  bird$count <- RemoveXHeaders(bird$count)
  bird.data <- as.matrix(bird$count[ ,-1])

  if (main.title == "")
    main.title = bird$name

  MakeSvgDirectory(cbc.code)

  blue <- rgb(0, 0, 1, alpha=0.65)

  if (generate.svg)
    svg(paste0("./svgs/", cbc.code ,"/", FileSafeName(bird$name), ".svg"), width = 12, height = 8)

  barplot(bird.data,
          main      = main.title,
          sub       = paste("CBC Data for", paste0("[", cbc.code, "]"), cbc.name),
          xlab      = "Years",
          ylab      = "Total Count",
          col       = blue,
          cex.names = 0.625,
          border    = NA,
          axes      = T,
          las       = 2)

  if (generate.svg)
    dev.off()
}
